//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transformer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Transformer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; encoding=&quot;UTF-8&quot; indent=&quot;yes&quot; cdata-section-elements=&quot;ESP_TEXT&quot;/&gt;
        ///
        ///
        ///&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;RTBF_Move_Export_file&gt;	
        ///	&lt;xsl:choose&gt;
        ///		&lt;xsl:when test=&quot;trailercampaigns&quot;&gt;
        ///		      
        ///			&lt;Informations_Generales&gt;
        ///				&lt;FullDate_Generation_File&gt;
        ///				      &lt;xsl:value-of select=&quot;trailercampaigns/exportinformation/timestamp/ESP_TIMEINSTANT/@full&quot;/&gt;
        ///				&lt;/FullDate_Generation_File&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string @__Export_PROMO_TEST {
            get {
                return ResourceManager.GetString("__Export_PROMO_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Attribute_32xMD {
            get {
                object obj = ResourceManager.GetObject("Attribute_32xMD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CollapseChevronDownGroup_24x {
            get {
                object obj = ResourceManager.GetObject("CollapseChevronDownGroup_24x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CollapseChevronUpGroup_24x {
            get {
                object obj = ResourceManager.GetObject("CollapseChevronUpGroup_24x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DependencyGraph_16x {
            get {
                object obj = ResourceManager.GetObject("DependencyGraph_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Exit_32x {
            get {
                object obj = ResourceManager.GetObject("Exit_32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ExpandAll_32x {
            get {
                object obj = ResourceManager.GetObject("ExpandAll_32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FilterFolderOpen_32x {
            get {
                object obj = ResourceManager.GetObject("FilterFolderOpen_32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Folder_32xMD {
            get {
                object obj = ResourceManager.GetObject("Folder_32xMD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FolderOpen_32x {
            get {
                object obj = ResourceManager.GetObject("FolderOpen_32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GreenCheckMark {
            get {
                object obj = ResourceManager.GetObject("GreenCheckMark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_Circled_Play_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Circled_Play_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_Indent_Filled_100 {
            get {
                object obj = ResourceManager.GetObject("icons8_Indent_Filled_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_Save_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_Save_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap InformationSymbol_32xLG {
            get {
                object obj = ResourceManager.GetObject("InformationSymbol_32xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap InformationSymbol_32xSM {
            get {
                object obj = ResourceManager.GetObject("InformationSymbol_32xSM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LinkedFolderOpen_16x {
            get {
                object obj = ResourceManager.GetObject("LinkedFolderOpen_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ProcessModel_32x {
            get {
                object obj = ResourceManager.GetObject("ProcessModel_32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RedCross {
            get {
                object obj = ResourceManager.GetObject("RedCross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Search_256x {
            get {
                object obj = ResourceManager.GetObject("Search_256x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Search_32x {
            get {
                object obj = ResourceManager.GetObject("Search_32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap String_32x {
            get {
                object obj = ResourceManager.GetObject("String_32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding = &quot;UTF-8&quot;?&gt;
        ///&lt;transmissions&gt;
        ///  &lt;exportinformation username=&quot;psi developer&quot; reportname=&quot;back loading report&quot; reportNumberOfTimesExecuted=&quot;128&quot;&gt;
        ///    &lt;timestamp&gt;
        ///      &lt;ESP_TIMEINSTANT time=&quot;11:37:37.680&quot; tvdayhours=&quot;11&quot; hours=&quot;11&quot; minutes=&quot;37&quot; seconds=&quot;37&quot; frames=&quot;17&quot;
        ///        duration=&quot;697:37.680&quot; durationinminutes=&quot;697&quot; durationinseconds=&quot;41857&quot; durationintimeframes=&quot;1046442&quot; date=&quot;2016-03-03&quot;
        ///        year=&quot;2016&quot; month=&quot;3&quot; day=&quot;3&quot; dayname=&quot;Thursday&quot; weekdaynumber=&quot;4&quot; weeknum [rest of string was truncated]&quot;;.
        /// </summary>
        public static string transmissions {
            get {
                return ResourceManager.GetString("transmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WebFolder_16x {
            get {
                object obj = ResourceManager.GetObject("WebFolder_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WrapPanel_24x {
            get {
                object obj = ResourceManager.GetObject("WrapPanel_24x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap XPath_32x {
            get {
                object obj = ResourceManager.GetObject("XPath_32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--
        ///    Copyright © 2001 World Wide Web Consortium, (Massachusetts Institute of
        ///    Technology, European Research Consortium for Informatics and Mathematics,
        ///    Keio University). All Rights Reserved. This work is distributed under
        ///    the W3C® Software License [1].
        ///
        ///    [1] http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231
        ///
        ///    Portions © 2004-2009 Microsoft Corporation.  All rights reserved.
        ///    This file was derived from http://www.w3.or [rest of string was truncated]&quot;;.
        /// </summary>
        public static string xslt {
            get {
                return ResourceManager.GetString("xslt", resourceCulture);
            }
        }
    }
}
